### ISSUE TITLE
Create.PolyCurve should throw warnings when input is incorrect

### ISSUE THREAD

**Issue by LMarkowski** [BHoM/Rhinoceros_Toolkit#113]
#### Description:

Create.PolyCurve(List<ICurve>) returns some strange curves if the input is incorrect. It's obvious in some cases but can be misleading as is showed in test file. Engine part is pretty clear, so issue might be in Rhino_Toolkit.

#### How to replicate:

Test file recreates logic from my code.

#### Expected behaviour:

Throwing an error.

#### Test file(s):

[Click](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRhinoceros%5FToolkit%2Fissue113%2DCreate%2EPolyCurveShouldThrowWarningsWhenInputIsIncorrect)

**Comment by LMarkowski** [comment]
@epignatelli are you familiar with the issue? 😃

**Comment by epignatelli** [comment]
The problem is just the ambiguity in the names.
Our concept of a `PolyCurve` is different from the Rhino equivalent.
We intend "a list of curves, whatever they are". Rhino intends http://docs.mcneel.com/rhino/5/help/en-us/popup_moreinformation/polycurve.htm

I agree that it is an issue when converting, you shouldn't see that.
Do you feel that, if the curves are not connected we should throw an error?

**Comment by epignatelli** [comment]
Yeah, the problem is that we do not check for that in the BHoM, so our schema is not that.
As you have shown in the test file, a user can create a `PolyCurve` made of disconnected lines.

I think the fix makes sense though, as it is a fix in the domain of a Rhino conversion 😆

**Comment by epignatelli** [comment]
I have hacked something, but I am not super happy with the setup.
![image](https://user-images.githubusercontent.com/26899347/67476772-95a5d300-f650-11e9-88e8-8657d6fd8c3b.png)
```sh
1. Data conversion failed from IGeometry to Curve
```
The problem is that you can create a BHoM `PolyCurve`, but then you cannot convert it to Rhino, which means that it is unusable in Grasshopper.

I think that if we do agree that our definition is different from the Rhinoceros one, what we have in #114 is ok.
If we believe that our definition of `PolyCurve` is not complete, we should throw an error when creating a BHoM `PolyCurve` with disconnected segments.
