### ISSUE TITLE
Brep not attaching to custom object as expected

### ISSUE THREAD

**Issue by harrilewis** [BHoM/Rhinoceros_Toolkit#168]
#### Description:
When I create a custom object within Grasshopper with Brep data I receive the following error:

"1. This component failed to run properly. Inputs cannot be collected properly.
The best overloaded method match for 'BH.Engine.Geometry.Query.CurveIntersections(BH.oM.Geometry.Arc, BH.oM.Geometry.Arc, double)' has some invalid arguments"

#### Steps to reproduce:
To reproduce it seems you need a Brep with an Arc as an edge.

#### Expected behaviour:
The Brep to be converted to BHoM.Geometry and back with no loss of data

#### Test file(s):
See attached Grasshopper file with internalised data.

[BrepConvert.zip](https://github.com/BHoM/BHoM/files/4906783/BrepConvert.zip)

**Comment by al-fisher** [comment]
As per @harrilewis's comments above. Seems to be an issue in converting Trimmed Nurbs with boundary's formed from curves out of the plane of the surface

See baked geometery - before and then after explicit casting to BHoM Geometry and back

![image](https://user-images.githubusercontent.com/15924573/87328001-c0142500-c52c-11ea-91b9-19aaa699ba46.png)

![image](https://user-images.githubusercontent.com/15924573/87328085-dfab4d80-c52c-11ea-9cd8-299e70e5e6b0.png)

**Comment by epignatelli** [comment]
It seems like we have some overloads for `BH.Engine.Geometry.Query.CurveIntersections` are missing?

**Comment by LMarkowski** [comment]
Hi @harrilewis,
After further inspection it seems that in most recent BHoM version this issue is no longer accurate.
I'm closing this one and opening another two that will be more up-to-date.
[Trimmed surface does not convert to BHoMGeometry correctly](https://github.com/BHoM/Rhinoceros_Toolkit/issues/170) - this one is probably the root of your issue.
[CreateCustom does not convert breps](https://github.com/BHoM/Grasshopper_Toolkit/issues/529)
Cheers!
