### ISSUE TITLE
Trimmed surface does not convert to BHoMGeometry correctly

### ISSUE THREAD

**Issue by LMarkowski** [BHoM/Rhinoceros_Toolkit#170]
#### Description:

Cannot explicitly cast Trimmed Surface to BHoMGeo. NurbsSurface is probably created correctly but cannot be exposed in Rhino.

#### Steps to reproduce:

See test file.

#### Expected behaviour:

Should convert to correct BHoM object.

#### Test file(s):

[On SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRhinoceros%5FToolkit%2FRhinoceros%5FToolkit%2DIssue170%2DTrimmed%20surface%20does%20not%20convert%20to%20BHoMGeometry%20correctly)

**Comment by pawelbaran** [comment]
I have just debugged the test file and found out that the convert fails due to tolerance issues: one of the values is 5e-6 and does not get caught by standard `BH.oM.Geometry.Tolerance.Distance`. Taken into account that the dimensions of the surface are in thousands, 1e-6 seems to be too strict and could/should be replaced with `BH.oM.Geometry.Tolerance.MacroDistance`. 

The questions are, however, where does the line between micro/standard/macro lie? Should it be based on the bounding box of a geometry? If so, should it take its maximum or minimum dimension? Or volume? Should the tolerance alignment be centralized? Inside Rhinoceros_Toolkit or globally across BHoM?

I think we already discussed it a bit, but never go to the final decision. Maybe it would be a good moment to try to tackle it? What do you think @al-fisher @rwemay @IsakNaslundBh @epignatelli?
