### ISSUE TITLE
Rhinoceros_Toolkit: Add support for converts of Extrusions

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/Rhinoceros_Toolkit#182]
#### Description:

Should be able to convert to and from Extrusions.

I know some initial studies has been done for this before with no success, but raising again to keep in mind.

**Comment by al-fisher** [comment]
Discussed this again the other day and again today 😄 
Think we are all in agreement that converts in first instance do not need to be reversible in order to facilitate the most valuable immediate workflows. 

i.e. focus on convert from BHoM To Rhino with the principle of:
BHoM.Geometery.Extrusion -> Rhino.BRep

@alelom @IsakNaslundBh @LMarkowski @pawelbaran

**Comment by al-fisher** [comment]
@rolyhudson 👆 might interest you! 😄
