### ISSUE TITLE
RandomPolyline returns a list of Points instead of a Polyline

### ISSUE THREAD

**Issue by LMarkowski** [BHoM/Rhinoceros_Toolkit#206]
#### Description:

As in header. Maybe it is an expected behaviour given it works on `Rhino.Geometry` objects, not `BH.oM`, but to me it's a bit confusing. 
![image](https://user-images.githubusercontent.com/48125514/111471807-95b4e000-8729-11eb-8fbe-a173c4d576a0.png)

#### Steps to reproduce:

Place `BH.Engine.Rhinoceros.RandomPolyline(int seed)` component on the canvas.

#### Expected behaviour:

Returning polyline.

#### Test file(s):

[SharePoint](https://burohappold.sharepoint.com/:f:/s/BHoM/EoWOGuaQIrlDidFQwQpCa9IBFKyQ7VCAz8R4Lyz8xHhPbA?e=pLmYxv)

**Comment by FraserGreenroyd** [comment]
Investigating the code for this issue during historic issue clean up, and it appears that the returned `Polyline` from the random method is a Rhino Polyline object, rather than a BHoM Polyline object. Thus the display in Grasshopper will be how it wants to display a Rhino Polyline.

Plugging the output into a `BHoMGeometry` component should convert it to a BHoM Polyline and display appropriately.

Thus I'm closing this issue as not needed for now based on that 😄
